apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ns.yaml
  - https://storage.googleapis.com/ml-pipeline/release/1.8.5/kfp-standalone-1.8.5.yaml
patches:
  - target:
      kind: Service
      name: ml-pipeline-ui
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
