apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  ports:
    - name: https
      port: 443
      targetPort: 8080
