name: old-infra-apply

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: myk8sPlayground-471206
  WORKLOAD_IDENTITY_POOL: projects/390106468834/locations/global/workloadIdentityPools/github-oidc
  WORKLOAD_IDENTITY_PROVIDER: projects/390106468834/locations/global/workloadIdentityPools/github-oidc/providers/github-provider
  SERVICE_ACCOUNT_EMAIL: gh-terraform-deployer@myk8sPlayground-471206.iam.gserviceaccount.com
  REGION: us-central1
  ZONE: us-central1-a
  CLUSTER: ml-gke

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT_ID"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/terraform
        run: terraform apply -input=false -auto-approve tfplan

      - name: Sync Argo Root App
        run: |
          kubectl apply -n argocd -f apps/root-app/app-of-apps.yaml
          # Wait and show app status
          kubectl -n argocd rollout status deploy/argocd-server --timeout=120s || true
          kubectl -n argocd get applications.argoproj.io || true